name: Static Code Analysis
permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

# For now, I want to see failures of jobs individually
#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

jobs:
  static_code_analysis:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.49.0

      - name: Install dependencies
        run: pixi install

      - name: typos
        run: pixi run typos

      - name: ruff check
        run: pixi run lint
        if: ${{ always() }}

      - name: ruff format
        run: pixi run ruff format --check
        if: ${{ always() }}

      - name: mypy-all (checking packages individually)
        run: pixi run mypy-all
        if: ${{ always() }}

      - name: mypy (checking packages together)
        run: pixi run mypy .
        if: ${{ always() }}

      - name: deptry
        run: pixi run deptry
        if: ${{ always() }}

      - name: bandit
        run: pixi run bandit
        if: ${{ always() }}

      - name: ochrona
        run: pixi run ochrona
        if: ${{ always() }}

      - name: pip_audit
        run: pixi run pip_audit --ignore-vuln GHSA-4xh5-x5gv-qwph
        if: ${{ always() }}
